### ISSUE TITLE
Write RFC for generic impact functions

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1180]

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 

Since we have generic impact functions (classified_hazard_building, classified_hazard_population, and continuous_hazard_population) [see #1471], is this issue (RFC) considered done? Or do we still have something more to do or implement related to generic impact function?

note: generic impact function is included in milestone for version 3.1 in implementation section. See : https://github.com/AIFDR/inasafe/milestones

Thanks

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - i think this is done. but not sure we have addressed @vdeparday original comments.
Closing this - @vdeparday - please open a new ticket if required
