### ISSUE TITLE
A3 Map template

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1314]
Create A3 map template in QGIS 2.6

**Comment by mahardika** [comment]
I have done creating the template using Arc 10.2 for both landscape and portrait. probably need the feedback from @Charlotte-Morgan first :)
if it is approved, I will re-make the template using QGIS 2.6

**Comment by mahardika** [comment]
Hi, I have tried to create some sample of the map templates for InaSAFE using QGIS 2.6.
please find the following samples and feel free to add some comments or suggestions.
regards


![q_a3_template_landscape](https://cloud.githubusercontent.com/assets/2441950/5972903/b96a3782-a893-11e4-8245-afdf982ddc9b.png)


![q_a3_template_portrait](https://cloud.githubusercontent.com/assets/2441950/5972910/c8c4cd46-a893-11e4-86ca-21393bdaf491.png)



cc @Charlotte-Morgan @timlinux @MariaSolovyeva

**Comment by timlinux** [comment]
These look very nice @dika - they will be a great addition to the collection of templates we have.

**Comment by Charlotte-Morgan** [comment]
hi @mahardika  these look great. I'd love to get them implemented.
Suggested next steps;
- [ ] run some 'standard' InaSAFE analyses and see if the design works with the type of information users will want to display. ie is there enough space for legend etc ..
- [ ] consult HOT @adissadis  and BNPB  for specific feedback, on the worked examples.
- [ ] get help to write new tickets for implementation. maybe @ismailsunni  or @akbargumbira can help with this.

**Comment by samnawi** [comment]
For the map template, i think is better if we add more information to put on there. So, InaSAFE just produce one page that include all of information that resulted by InaSAFE. Based on the experience, some user / decision maker will quickly understanding about the information, if we put all of main information in one page. May be, this issue is similiar with #1775 that @Charlotte-Morgan referenced.

**Comment by samnawi** [comment]
I've tried to create some InaSAFE map template for portrait and landscape in A3 format.
![flood_landscape_r](https://cloud.githubusercontent.com/assets/8871958/7410837/beea7806-ef5c-11e4-87cd-fd6014c16778.jpg)
![flood_portrait_r](https://cloud.githubusercontent.com/assets/8871958/7410838/bf19f55e-ef5c-11e4-9b76-b425252d8e00.jpg)

I also include some layout templates that can be downloaded in this link :
https://www.dropbox.com/sh/n5k9lh8yp5q5iqv/AABlpmuChGaBp55YGmH9a0Oba?dl=0

There is some note about this template :
1. I put the orange color in the top to harmonize with the BNPB map.
2. I suggest to put some impact report like summary for total of people affected, evacuation, or the building affected, but it just the general information, not detail. Because in the previous map, i saw the more free space in there.
3. Can we add the toponymy or administrative boundary? so it's not like a blind map.
4. I think it be better if there is an inzet map, Can this composer do auto detect the area will be show in inzet? For example, if we use jakarta, it's in Indonesia, the inzet will set up to Indonesia, but when this tool if use for Cape Town, the inzet will be automatically set up to South Africa.

Please fell free to give some comment and suggestion about this.

Thank you.

cc @Charlotte-Morgan @timlinux

**Comment by timlinux** [comment]
@samnawi These are looking really great.

> 1. I put the orange color in the top to harmonize with the BNPB map.

OK

> 2. I suggest to put some impact report like summary for total of people affected, evacuation, or the building affected, but it just the general information, not detail. Because in the previous map, i saw the more free space in there.

Yes - we just need to carry over the needed tags to the report

> 3. Can we add the toponymy or administrative boundary? so it's not like a blind map.

This is more tricky - we cannot easily pre-suppose which layers a user has. 

>4. I think it be better if there is an inzet map, Can this composer do auto detect the area will be show in inzet? For example, if we use jakarta, it's in Indonesia, the inzet will set up to Indonesia, but when this tool if use for Cape Town, the inzet will be automatically set up to South Africa.

One option would be to actually show a global countries dataset with InaSAFE and then use that. There are a few free alternatives that we could do this with.

**Comment by Charlotte-Morgan** [comment]
Hi @samnawi 
Thank you for updating this ticket. and for your efforts to solve this neatly.

- [ ] I like the way you harmonize with the BNPB map - ticket #752 .  I think this also uses colours from the InaSAFE style guide Maria? - are you also able to use the fonts from the InaSAFE style guide?

- [ ] Getting the map and report on a single page is important and also challenging. Considering they both had equal space before as single page reports; I would be tempted to give them a bit more space. do you think 1/3 allocation to map, 1/3 report and 1/3 marginalia (including inset map) would be a good balance.

- [ ] I agree that the maps should include some context such as admin boundaries, place names or roads to help the readers. However I think this is something that users should be encouraged to manage & that the legend for these additional data should be minimal if at all. Maybe a warning or advice to users to turn on other data they want to see on the map & ensure this is covered in the training materials (note to HOT on curriculum - using map composer - I'm sure you already cover making maps useful, can you also look at using templates and adding personal touches if its not already there @adissadis @iyan31 ).

- [ ] @samnawi - i think it would be great to prepare a 'base' data set of admin boundaries and place names for Indonesia with symbology, labels and scale dependencies that we can share. Please make yourself a ticket for this :)

- [ ] Inset is a valuable addition - hopfully it can auto zoom. If necessary, please prepare a dataset to sit behind this based on feedback from @timlinux. In theory this is the same basemap dataset above but would be very basic at a national scale.

- [ ] can you reach out to HOT and BNPB maybe for some comments / feedback too?
- [ ] @fredychandra - can we include this on the ITWG meeting agenda?

**Comment by timlinux** [comment]
Another thing we could do is get @Gustry to extend the OSM downloader to also download OSM political boundaries as another layer, and then set up canned, beautiful, localised styling for them like we have done for roads.

> I like the way you harmonize with the BNPB map - ticket #752 . I think this also uses colours from the InaSAFE style guide Maria? - are you also able to use the fonts from the InaSAFE style guide?

One problem with this is that we would need to ship the fonts with the plugin and also figure out an operating system independent way to use those fonts. We will need to research a bit to see how easy that will be.

@MariaSolovyeva Could you provide review of the mockups above?

**Comment by samnawi** [comment]
@Charlotte-Morgan, thank you for the feed back, 
1. Yeah, i use the the HEX: #f57d35 color for the orange color in the top.
2. I also try to use the proportional portion like i've been discussed using sketch with you 3 weeks ago.
3. For the toponymy or admin boundary, i agree with you to prepare a data that can be shared. @timlinux can we set the data in server such as geonode, geoserver or the other, and then we use that mapservices to automatically mapped in QGIS.
4. Ok, i'll try to reach out our colleague in BNPB and HOT to comments this map.

**Comment by timlinux** [comment]
> 3. For the toponymy or admin boundary, i agree with you to prepare a data that can be shared. @timlinux can we set the data in server such as geonode, geoserver or the other, and then we use that mapservices to automatically mapped in QGIS.

I would prefer if we can make this work in a generic way from OSM downloader rather than having to provide access to multiple online services. @iyan31 and @Gustry should be able to provide more input, but there are standard tags for pulling out admin boundaries from OSM that we can make use of.

**Comment by Gustry** [comment]
@timlinux @samnawi Which administrative level in OpenStreetMap do you need ?
Do you want each level in a layer, or every levels in one layer ?
You can have a look at this page to help : http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#11_admin_level_values_for_specific_countries

**Comment by Charlotte-Morgan** [comment]
my guess is separate layers with scale dependency - like the roads bundle

**Comment by samnawi** [comment]
@Charlotte-Morgan I've been tried to make 2 InaSAFE maps template, after get the training from @timlinux to use element-ID also Element-Tokens.

I try to revise current map template to harmonize with BNPB's Map (with orange color in header).
This is the result for landscape and portrait format in A3 size.

Landscape
![merapi_landscape_1](https://cloud.githubusercontent.com/assets/8871958/8203002/ed126244-1508-11e5-8ebb-1f660d941710.jpg)

Portrait
![merapi_portrait_1](https://cloud.githubusercontent.com/assets/8871958/8203173/1de5ee30-150a-11e5-8489-a228ce5317fe.jpg)

1. In the current version, there is no scale bar, so I add the scale bar in the map template, but I still confuse to setting this scale bar parameter, because I still not find a parameter to keep the length of this scale bar, so the length of scale bar is will be locked. Sometimes, when the area is larger, the scale bar is also longer.

2. And also, could we change the InaSAFE's logo that used in the current version to this logo?
![selection_022](https://cloud.githubusercontent.com/assets/8871958/8203296/e3bb63ce-150a-11e5-8269-1e734ca66424.png)
In my expectation, the header of the map become like this 
![header](https://cloud.githubusercontent.com/assets/8871958/8203323/16dc32c4-150b-11e5-853d-fd09fd02137b.jpg)

3. Could we also change the north arrow style with this
![north_arrow](https://cloud.githubusercontent.com/assets/8871958/8203385/98afc036-150b-11e5-83a9-2ad72a825f42.png)
I think it looks nice.

4. In my mind, I still have an expectation to put some general report, sources of the data, information about the coordinate system, and the overview map to fill the empty area in the map template.

This is the link to download the *.qpt files
https://www.dropbox.com/sh/81k4mx353akx395/AAD0LZw5o0C4DkdtQXAfWQdIa?dl=0

Let me know if there are some comments about this templates.
@MariaSolovyeva please give me some advice about the map composition.

Thank you.

**Comment by timlinux** [comment]
CC @wonder-sk

**Comment by Charlotte-Morgan** [comment]
hi @samnawi - will we be able to have this ready for 21 August ?

**Comment by Charlotte-Morgan** [comment]
@samnawi - can you have this ready for 21st August?

**Comment by samnawi** [comment]
@Charlotte-Morgan Is There any feedback from that was I posted?
I'll prepare it to ready before 21st August

**Comment by Charlotte-Morgan** [comment]
can you please print some samples

**Comment by samnawi** [comment]
OK @Charlotte-Morgan

**Comment by samnawi** [comment]
@Charlotte-Morgan I've tried to revised some a few thing from the last templates that I posted.
This is the preview :
Portrait
![nagekeo 3](https://cloud.githubusercontent.com/assets/8871958/9381195/67bcac88-475f-11e5-9fbd-9637771aba2d.jpg)

Landscape
![maumere landscape](https://cloud.githubusercontent.com/assets/8871958/9381264/e5b9528a-475f-11e5-93b9-729e7ed37a66.jpg)

1. I throw away the scale bar, because the scale bar will be very long (uncontroll) when the OTF in QGIS is not activated. If the OTF is not activated, the scale bar will look like this :
![selection_118](https://cloud.githubusercontent.com/assets/8871958/9381307/4f704350-4760-11e5-83f7-55876a75f9a4.png)
2. I try to give some orange color on each part, so it look like nice. But, I get some trouble in the legend when the template is used to tsunami and flood on roads IF. The trouble is look like this
![selection_119](https://cloud.githubusercontent.com/assets/8871958/9381468/c95b8962-4761-11e5-83e3-3f74cdc7bb78.png)

Whereas, when I used it in the other IF, the legend is fine.
![selection_120](https://cloud.githubusercontent.com/assets/8871958/9381562/b84102e6-4762-11e5-91ca-6e6098788953.png)
Should I remove the orange color in this part? or there are some solution and comments about this templates.

The *.qpt files can be downloaded in this link
https://www.dropbox.com/sh/ruw4k0lpo4uwoor/AACbLatyjdgvHQYyAj9TBmmCa?dl=0

Thank you

cc: @timlinux

**Comment by Charlotte-Morgan** [comment]
hi @samnawi - thank you for all the work you have done on the templates. I really like the changes you have made and the orange highlights. I agree that the other InaSAFE logo looks better in the header.  I think this is good to go with the logo change
@timlinux - is @wonder-sk able to help take this work to production?

**Comment by timlinux** [comment]
Hi

Sorry I commented on this earlier but my comments never got committed it seems.

@samnawi This is really great -  I tested here and it works well against a 'real' analysis:

<img width="573" alt="screen shot 2015-08-24 at 23 44 45" src="https://cloud.githubusercontent.com/assets/178003/9453491/0bf9c78c-4abb-11e5-9f5e-18e581af4863.png">

Regarding your scalebar issue - there is a fix for this coming in the next LTR release. In the mean time using a word scale is a good option.

I will cross reference this issue with a PR to apply it to develop for 3.2 - thanks!

**Comment by samnawi** [comment]
@timlinux Thank's to follow up this stuff.
Yeah, for the scalebar issue, as the advice from @Charlotte-Morgan using a word scale will make a confuse if user will print it in various paper size. Because the word scale is fixed, not flexible like we use a scalebar when it will printed in various paper size, while I set this template in A3 format.

For the scalebar fix width, it's available in 2.10. But it's still complicated when the user not active the OTF (On The Fly Projection).
This is the scalebar if OTF is not activated
![image](https://cloud.githubusercontent.com/assets/8871958/9459182/dc747cec-4b22-11e5-9cb5-a989bea59180.png)

This is the scalebar if OTF is activated
![image](https://cloud.githubusercontent.com/assets/8871958/9459196/f7612df2-4b22-11e5-8ca8-409df3dfea60.png)
