### ISSUE TITLE
Add Allow Resampling Options to Wizard

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1365]
# Problem
Script from out InaSAFE hipchat channel
```
Assefa Yewondwossen
4:49 AM
@CharlotteMorgan @AkbarGumbira regarding the question about specifying the resolution of the result: the way it is setup is that the user defines a key word on the exposure layer "allow_resampling=false". That will gurantee that the resulting layer will have the same resiltion than the exposure layer. It works of course for both exposure and hazard being raster layer. 
Maybe the ideal way would be to have it presented for the user would be through the wizard interface?
Tim Sutton
12:22 PM
@Assefa yes that is a good idea - @IsmailSunni can you add that to the task list for Borys? Just a tickbox on the keywords editor for raster layers should do it
```

# Proposed Solution
Perhaps default option `allow_resampling` on the wizards when the layer is raster

# Expected Outcome
There is an easy way for user the set the value of `allow_resampling` if the layer is raster.

**Comment by borysiasty** [comment]
Is it about possibility to set the value by user or is it just fixed by #1078 ?

**Comment by akbargumbira** [comment]
It's different. When we have population density (detected by keyword), we must set allow_resampling to False. 

Thia is more of an option for user. If the exposure layer is raster, we should give option to them if they want to resample it (technically just adding allow_resampling keyword based on the chosen option on thw layer )

**Comment by borysiasty** [comment]
@akbargumbira: ok, so just for sure:
1. For exposure rasters with unit 'people_per_pixel', the keyword is automatically set.
2. For exposure rasters with other unit, the user is asked about it.
3. For any other layers the keyword is not set.

**Comment by akbargumbira** [comment]
@borysiasty:
1. Basically for density data yes, the keyword allow_resampling should be set automatically to False
2. Yes
3. Yes. It's only for exposure layer.

**Comment by akbargumbira** [comment]
@borysiasty, I just had a look at your changes here https://github.com/AIFDR/inasafe/commit/cbed05c0a7ec9371f756842c9b0df1eee83aa11d

```
 # Set allow_resampling to false if unit is people_per_pixel
 if is_raster_layer(self.layer) and keywords['unit'] == 'people_per_pixel':
 keywords['allow_resampling'] = 'false'
```

Density data is not recognised by unit people_per_pixel though (see safe/metadata.py for its explanation). I am not sure if we have metadata to define density data. @ismailsunni or @timlinux can answer that

**Comment by borysiasty** [comment]
So the final conclusion is:
1. For exposure rasters with unit 'density' (not used currently), the keyword is automatically set to false.
2. For exposure rasters with other unit, the user is asked about the keyword value.
3. For any other layers the keyword is not set.

**Comment by Charlotte-Morgan** [comment]
hi @borysiasty  et al; Sorry to get involved in this conversation but I think things have got a little confused here. Here are a few background points for your consideration.

1. For raster on raster analysis; since the IF results are reporting against the exposure data, the exposure data should not be resampled. ie the output of the analysis should be the same cell size and same cell alignment as the input exposure raster. This should be the default situation. @assefay suggestion to add a key word "allow_resampling" will allow users to change this if the default does not suit their analysis requirements.

2. allow_resampling = false should apply regardless of whether the exposure data have a unit of density or people_per_pixel. This basic raster analysis logic has nothing to do with the unit.

3. Subsequent to many of the related discussions, we agreed to change the default population raster exposure unit from "density" to "people_per_pixel". The reasons for this:
* the exposure data are count data not density data
* inasafe analyses are calculated in geographic coordinates so pixel areas are not constant

4. We should not preclude the use of density data in the future - in fact it would solve many many problems if InaSAFE operated on projected data ... :)

@maning @assefay @timlinux @akbargumbira - please correct or update as required

**Comment by akbargumbira** [comment]
Hi @borysiasty, I had discussion with @Charlotte-Morgan about this. I was giving incorrect fact that we should always set allow_resamping=False when the exposure raster layer is density layer (I got that fact from this ticket from @timlinux https://github.com/AIFDR/inasafe/issues/1078 - Wizard should write allow_resampling = False for population density exposure)

So, I guess user is always asked whether they want to resample their population exposure raster layer or not.

**Comment by borysiasty** [comment]
@Charlotte-Morgan , @akbargumbira: So what is the final conclusion :) Should the wizard display the Resampling step for any raster, or exposure raster only?

**Comment by Charlotte-Morgan** [comment]
@borysiasty - i think its only relevant to Exposure raster. But the people writing IF should confirm.
@timlinux @assefay @maning

**Comment by akbargumbira** [comment]
@borysiasty @Charlotte-Morgan, right now the allow_resampling keyword only works for exposure raster only. There won't be any effect if you specify allow_resampling keyword on hazard layer

**Comment by akbargumbira** [comment]
@Charlotte-Morgan right now, Impact Function does not care about our clipping/resampling method. It will run the layers (exposure, hazard) that are feed to it.

**Comment by borysiasty** [comment]
So the final question is what we need: 

 - just one checkbox for allow_resample=false (not checked by default, and, unless checked, the allow_resample keyword is not put to the keywords at all)

 - as above, but allow_resample=true is set instead of not setting it at all

- we rather need all three cases: allow_resample=false, true and not set

**Comment by borysiasty** [comment]
I added a new step after setting the unit (or directly after the data_type if no units available for categorical data). As I wrote above, it doesn't create the allow_resample keyword at all unless checked (can be improved for ver 3.1). 
![allow_resampling](https://cloud.githubusercontent.com/assets/1000043/6000874/c70c2146-aae3-11e4-922c-d36677be6b56.png)

@Charlotte-Morgan @timlinux: please check and probably improve the texts above :) It's the allow_resampling_question constant in the wizard file.
