### ISSUE TITLE
[IFCW] Better Keywords Displaying

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1466]
Problem
----------
See blue box in the image below
![inasafe_022](https://cloud.githubusercontent.com/assets/1421861/5612177/4a2e1422-9503-11e4-8e28-4012e0a66096.png)

Some Ideas for Solution
--------------------------------
- [x] Use invisible table to separate keys and values (keys to left column, values to right column)
- [x] Use title case for keywords
- [x] Use UN OCHA disaster icons to provide more visual context. E.g. show flood icon when displaying flood hazard.

Expected Result
----------------------
Keyword is shown more beautiful and neat :)

cc @timlinux

**Comment by borysiasty** [comment]
@ismailsunni, do you mean title case in keyword values or keys?

**Comment by borysiasty** [comment]
@Charlotte-Morgan @timlinux @ismailsunni @akbargumbira: Now, with the IF matrices (see #1525), this step should probably only display layers with the selected subcategory, shouldn't it? So it's redundant to display the subcategory on the right. Also category and title is redundant... Maybe instead of the keyword table we should put a more userfriendly sentence like "This **flood** layer (yes, it's still redundant) is measured in **m** and comes from **HKV**"? I don't have any good idea for it.

**Comment by ismailsunni** [comment]
Hmm, perhaps the sentence above it, we can put a string like : "Here all [flood] hazard [raster] layer that are loaded in QGIS" *or something like that.

And for the keywords, I agree to use more user-friendly sentence like that.

**Comment by borysiasty** [comment]
Ok, tephra is going to be removed from the matrix, so the list can't be filtered by subcategory.

**Comment by Charlotte-Morgan** [comment]
i dont understand this

**Comment by borysiasty** [comment]
Ok, now I got it

**Comment by borysiasty** [comment]
This issue is mostly obsolete. I move it to 3.1 to not forget to make nicer description for the function.
