### ISSUE TITLE
Impact functions options dialog: options tab

### ISSUE THREAD

**Issue by Jannes123** [AIFDR/inasafe#1762]
update impactfunctions options dialog dynamic tab creation function to build widgets using parameter containers

#1689

**Comment by Jannes123** [comment]
We need to builda custom Dict- and List-ParameterWidget class in order to display all the parameter types

**Comment by Jannes123** [comment]
Finished building DictParameterWidget

**Comment by Jannes123** [comment]
Just committed a ListParameterWidget class just for testing my own code.  @rizky please let me know how it goes I will also try to update some IFs after I integrate with christiaans latest work.

**Comment by lucernae** [comment]
I've read your commit. @Jannes123 , it is more or less the same idea with what I currently build. But, as I remembered, @timlinux mentions that we wanted to use something like QListWidget so we can select the options. I also made my changes in the AIFDR/parameters repo so we can easily replace safe_extras/parameters package. 

For the last concern that I thought, I think we should make the dict_parameter_widget and list_parameter_widget in safe_extras/parameters/qt_widgets instead. But, perhaps you decided to put it in safe/common because we already have resource_parameter_widget.

So, for these 2 things that I pointed out, I think we should hear the other's opinion about this. For now, I think we should leave both implementation available and then we can merge the difference later after we can decide which one we want to take.

**Comment by Jannes123** [comment]
Thanks @lucernae the changes look good to me can you please do a PR to my branch build_widget on inasafe so we can continue the reworking of the parameters with your changes included.   I'm not entirely sure how the inasafe and parameters repos work together but for now I think you can just copy your files in after you pulled buiuld_widget and commit.

**Comment by Jannes123** [comment]
Being absorbed into #1816
