### ISSUE TITLE
BUG: Pyton error - Volcano on population

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1796]
```
Details

These additional details were reported when the problem occurred.

An exception occurred when calculating the results. Calculation error encountered:
cannot convert float NaN to integer
Diagnostics (click for details)

In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\impact_calculator_thread.py", line 188, in run check_integrity=self._check_integrity)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\engine\core.py", line 184, in calculate_impact F = impact_function.run(layers)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_functions\volcanic\volcano_polygon_population\impact_function.py", line 181, in run population = int(categories.get(key, 0))
``

**Comment by akbargumbira** [comment]
This is more likely that the population data has NaN value (probably when we encounter the NoData value and numpy treats it as NaN). @cchristelis can you look at this?

**Comment by lucernae** [comment]
Does anyone resolves this issue?

**Comment by akbargumbira** [comment]
@lucernae I will resolve this in my branch (generic_polygon). This NaN issue should be informed to the user though (that's why I assigned this to Christian). User should know if they have no data value in their raster data and how we treat it in the analysis. In some cases it makes sense to treat it as 0 (e.g for counting total population in raster representing people count), but not in other cases (e.g in classified raster hazard data)

**Comment by akbargumbira** [comment]
Fixed here https://github.com/AIFDR/inasafe/pull/1871
