### ISSUE TITLE
No Data: we need to standardise the way we handle no data

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1800]
# problem
we need to identify a suitable  / standard way to handle nodata values 

# proposed solution
the no data value should by default not be the same as a valid data value and should not be included in calculations or interpolation.

eg, a value of 0 is not acceptable as a nodata value if that is a valid data value (eg flood depth) as this will influence the analysis results

eg a value of 0 in a flood or population raster implies that there is no water or no people. the no data value says we do not know how many people or how deep the water. using a value of 0 in this case would be very misleading

# other standards
in ESRI software, the standard is to use -99 as the nodata value.

Is there a standard in QGIS and should we introduce something for InaSAFE analyses?

#cc
@timlinux @iyan31 @akbargumbira @KathrynOwen

**Comment by Charlotte-Morgan** [comment]
some impact functions convert the no data value to NaN and this will raise an exception. The ValueError message does not necessarily advise the user that this is the problem.

**Comment by iyan31** [comment]
Hi @Charlotte-Morgan, I just asked the team yesterday, in the training for no data they simply left it blank or in QGIS this would mean NULL. I think it may be possible to sanitize the input (ex. detecting if value is NULL) in the impact function and then convert it into something processable.

**Comment by akbargumbira** [comment]
These are the IF's that treat nan in the data as 0: continuous hazard population function, flood population evacuation raster hazard function, tsunami population evacuation raster hazard function, volcano point population, volcano polygon population

**Comment by Charlotte-Morgan** [comment]
I tested with the current develop version as at 4pm 22nd April 2014 (jkt time)
- [ ] Jakarta Flood Raster on Raster population - runs no error with both user defined and full extent
- [ ] Jakarta Flood Polygon on Raster Population - runs no error with both user defined and full extent
- [ ]SS EQ Hazard Zone polygon on Raster Population - error with analysis area set over the data edge or when analysis extent defined by the window.
I saved the scenario files but they are on the other pc ... sorry

**Comment by Charlotte-Morgan** [comment]
yesterday - there were issues with jakarta too. but not now

**Comment by akbargumbira** [comment]
Just a note for this. For Flood Polygon on Population, Classified Polygon on Population, Volcano Point/Polygon on Population, I treat Nan in the exposure as 0 when counting the affected population / total population. I added a sentence telling that in the Notes section of the impact result

**Comment by cchristelis** [comment]
When null values are present they affect the output. The important issue is that they are not when we are doing raster on raster operations these null values should be carried through to the output.
This was done in PR #1898 together with a warning "`No data` cells where detected in the population layer. This may affect the result.". 

Also other warnings where made conditional. This may be revised since, as @akbargumbira pointed out, it is better to always inform the user about the handling of data.

# Rounding is still an open issue. 
My current suggestion is bilinear where we have sufficient data points, else substitute missing data points with averages. Although this might not be the best solution, this will allow us to do minimal checking and simple substitution as needed rather than using alternates extrapolation methods. Any thoughts on a better approach?

**Comment by Charlotte-Morgan** [comment]
i think nodata should persist and not be interpolated. 
nodata in population should not affect results if we are summing ie total people affected
will affect density - but we are not calculating density.

no data in hazard should also persist

**Comment by cchristelis** [comment]
Ok, that means that we are done with this.
