### ISSUE TITLE
Wrong text for Raster Exposure Wizard

### ISSUE THREAD

**Issue by vdeparday** [AIFDR/inasafe#1859]
The text describes a Hazard layer rather than an exposure one and also mode continous and discrete are suggested when I am not sure if both are supported with exposure:
![screen shot 2015-04-21 at 6 23 24 pm](https://cloud.githubusercontent.com/assets/1036189/7257124/a7c4c790-e853-11e4-9ed8-00ef9bc93c41.png)

**Comment by timlinux** [comment]
@ismailsunni So basically it would be good to have logic that says 'do any IF's support population as classified raster?' and then if not, don't allow the user to choose classified. 

@vdeparday with regards to the reference to hazard or exposure, for me they are ok since the explanation is a generic one and it is not implying whether the data is one or the other.

**Comment by ismailsunni** [comment]
This ticket is already fixed in the new wizard. Closing this....
