### ISSUE TITLE
Flag when bounding box covers only a few raster pixels 

### ISSUE THREAD

**Issue by uniomni** [AIFDR/inasafe#188]
Suggestion from John Scheider. It'd be good to communicate when the selected bounding is so small that one of the input rasters has only a few pixels in it. 

That will affect the quality of the output. In fact, this might link to the idea of associating quality to the output layer based on quality of input layers and impact function: See https://github.com/AIFDR/inasafe/issues/37

See also #185

**Comment by cchristelis** [comment]
I have created a little pixel counter script, that counts the number of pixels for a raster on a canvas. The script is in the following gist:
https://gist.github.com/cchristelis/29f89c854b375ec7f9ef
and can be tested out with a raster layer as the first layer in QGis.

This will be ideal as a validator in the new style IFs. The question is how many pixels will be a suitable amount to start issuing the warning. Since we are developing this concept in #1234, I'm closing this issue in favor of continuing there.
