### ISSUE TITLE
We need to make Flood Polygon on Buildings faster

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#1889]
# Problem
Now that we removed the old style IF for this, we need to make the QGIS IF one faster. Running FLood Polygon on Buildings with Jakarta extent takes intolerable time for user to wait.

# CC
Perhaps @cchristelis or @timlinux can address this?

**Comment by timlinux** [comment]
Hi

Yes I agree we should make it faster. Through for me a higher priority is to get a good feedback mechanism in place so that the user can see how far the analysis has progressed (and cancel it if he gets bored). I don't think that we can expect to always deliver instant results to the user, but making them understand what the status of the analysis is will allow them to feel comfortable that 'something is happening'.

I noticed this especially with e.g. the pleaides dataset that @vdeparday was using the other day - the polygons are so complex there isnt any easy way to make the geometry operations very fast with them - even under postgis (which is regarded as very well optimised code) the operations took ages.

**Comment by timlinux** [comment]
@wonder-sk perhaps we can get you to take a look at this and come up with some improvements?
