### ISSUE TITLE
BUG: Insufficient Overlap

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1927]
# Problem with raster on raster analysis

```
Problem

The following problem(s) were encountered whilst running the analysis.

InsufficientOverlapError
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details

These additional details were reported when the problem occurred.

A problem was encountered when trying to determine the analysis extents.
There was insufficient overlap between the input layers and / or the layers and the viewable area. Please select two overlapping layers and zoom or pan to them or disable viewable area clipping in the options dialog. Full details follow:
Failed to obtain the optimal extent given:

Hazard: C:\AIFDR\GA-TAP\12_TrainingMaterial\1503 InaSAFE 3.1 Demo Kit\Data\Flood_HKV_Jakarta.tif
Exposure: C:\AIFDR\GA-TAP\12_TrainingMaterial\1503 InaSAFE 3.1 Demo Kit\Data\POP_Indonesia.tif
Viewable area Geo Extent: [0.000958230955242974, -5.728120885303982e-05, 0.0009611521687490971, -5.4660230275569265e-05]
Hazard Geo Extent: [106.68597429495, -6.3734208271403, 106.97453416473836, -6.079885787183174]
Exposure Geo Extent: [95.05902541031102, -10.997474511110997, 141.00718741031102, 5.907682588889002]
Viewable area clipping enabled: True
Details: Bounding boxes of hazard data, exposure data and viewport did not overlap, so no computation was done. Please make sure you pan to where the data is and that hazard and exposure data overlaps.
Diagnostics (click for details)

In file "C:/Users/localadmin/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1188, in accept self.analysis.setup_analysis()
In file "C:/Users/localadmin/.qgis2/python/plugins\inasafe\safe\utilities\analysis.py", line 713, in setup_analysis raise e
```

**Comment by timlinux** [comment]
Is this on the release version @Charlotte-Morgan ?

And can you tell me what steps you followed so I can replicate it?

**Comment by Charlotte-Morgan** [comment]
data: jakarta flood raster, popmap_all population raster.
Environment: fingers crossed, hold breath, squint
analysis extent: clear - then zoom in, or set etc nothing happy

**Comment by timlinux** [comment]
I'm trying to replicate here:

This is with flood raster and pop, extents cleared and zoomed in:

![noclipping](https://cloud.githubusercontent.com/assets/178003/7606262/84c7d132-f957-11e4-97d4-756e44170dfd.png)

I get this:

![screen shot 2015-05-13 at 10 01 00](https://cloud.githubusercontent.com/assets/178003/7606272/972ff1d8-f957-11e4-8b4b-a2ae86ff97d5.png)


Enabling clip to view:

![screen shot 2015-05-13 at 10 06 51](https://cloud.githubusercontent.com/assets/178003/7606299/d55dee92-f957-11e4-8fd1-058ea1413d34.png)


I get:

 

![screen shot 2015-05-13 at 10 07 42](https://cloud.githubusercontent.com/assets/178003/7606319/ec738682-f957-11e4-84be-2db5e6f24dde.png)



@Charlotte-Morgan also mentioned off-list that:

>The error appears when I try to run an analysis in a saved project file. 
> If I load the same data but do not save it works. 
> This seems independent of analysis extent setting and updated key words. 

In the tests above I was also using a saved project file, without issue.

One other thing I will test is using the package from experimental rather than my local source tree.

**Comment by timlinux** [comment]
I tested again using the new extents selector branch - every permutation worked fine. I'll close this out for now - please reopen if the issue reappears.
