### ISSUE TITLE
Move to IF base class the target field and other necessary hardcoded options in current IF's

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#1959]
# Problem
For the case of vector impact layer, we sometimes need to specify the target field in the impact layer and other variables (for example the string to write to the data when it's not affected). It will be nicer to move this to IF base class. With this in place, we can have:
1. Once in base class checking that the target field is not conflicted with the existing fields from input layers. We have already a function for that get_non_conflicting_attribute_name and just needs to use this in the base class.
2. A standardized output for all IF's related.

**Comment by timlinux** [comment]
Can you point to a specific example of where we do this for the logs of this ticket? I wonder if it would not be nicer to:

* Strip original attributes from the impact layer
* Create a foreign key reference to the original layer in QGIS so user can still see the original attributes
* Use a simple algorithm to ensure that ``get_non_conflicting_attribute_name`` returns a guaranteed unique attribute name (either the requested name if it is not used, or a truncated version + hash if it is used).

My thinking is that with large datasets we essentially propagate the whole dataset to the impact layer instead of just the key pieces needed to reflect the impact. Just a thought anyway, your approach will be fine with me too.

**Comment by akbargumbira** [comment]
This PR addresses this https://github.com/AIFDR/inasafe/pull/1970. Note that some of the code will be changed again when I do the analysis streamlining. Closing this
