### ISSUE TITLE
[Bug] Several windows not resizeable

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#2021]
# Problem
I found that several InaSAFE window is not resizeable as usual. Those windows are:
* InaSAFE Wizard
* InaSAFE OpenStreetMap Downloader
* InaSAFE Impact Function Centric

Here are the screenshots i got from each features that not resizeable:
![inasafe_2](https://cloud.githubusercontent.com/assets/2520159/8050282/c7e7867c-0e94-11e5-96d3-0b7d44e8b4e1.png)

![inasafe_3](https://cloud.githubusercontent.com/assets/2520159/8050283/c7e9001a-0e94-11e5-91ca-a1b60928b1b8.png)

![inasafe_1](https://cloud.githubusercontent.com/assets/2520159/8050284/c7f0aa5e-0e94-11e5-8821-3fbb5670ac5e.png)

# Operating System
I'm using Windows 7
QGIS 2.8.2 
Recent InaSAFE 3.2 (just sync with this repository at 10.30 AM 9 June 2015)

**Comment by ismailsunni** [comment]
hi @timlinux or @borysiasty 

It seems it should be similar with #1484. May be you can check this one out

**Comment by borysiasty** [comment]
I was sure my commit 3f2e89fdedfb fixed this problem previously... The reason is MessageViewer extending without limits. After lots of tries and experiments with the layout resizing policies the only way I found was to explicitly set the MessageViewer's maximumHeight. Now it seems even it doesn't help.

MessageViewer inherits from QWebKit, and QWebKit is directly used in OSM Downloader, so it must be the culprit. I'll be investigating it in the end of this week.

**Comment by timlinux** [comment]
@Gustry can you put the osm downloader in a QScrollArea as a short term fix?

**Comment by Gustry** [comment]
@adissadis @timlinux Done in the OSM Downloader

**Comment by timlinux** [comment]
Could you confirm if this is still an issue in develop?

**Comment by lucernae** [comment]
@adissadis said it is still in develop

**Comment by lucernae** [comment]
fixed from @timlinux PR
