### ISSUE TITLE
We need to reconsider how we handle default hazard values.

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2036]
# Problem
In definitions.py I see that some default settings that are not great for impact functions.

example
 key: volcano_vector_hazard_classes
default_class: high #unclassified values will go to this class

# proposed solution
Maybe unclassified values in all hazard data should default to a state where they can  not be used for an impact analysis. ie be handled like 'nodata'

# cc
@timlinux

**Comment by ismailsunni** [comment]
I agree with @Charlotte-Morgan 

My opinion, let's remove this default thing. Since unclassified value should be considered to "it won't be calculated". And state in the description that unclassified values will not considered in the calculation. (similar to `nodata` but just make sure that this is not editable)

It's easy to remove this since we haven't used this in any part of InaSAFE. (@borysiasty correct me if you uses it in the wizard)

**Comment by timlinux** [comment]
+1 - I think data should be explicit when it comes to defining what is a hazard.
