### ISSUE TITLE
Type Error: Flood on building

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2167]
# Problem
InaSAFE fails to run flood polygon impact on building polygons
QGIS 2.8.2, InaSAFE 3.2, Windows 7 64 bit.

# Error Message
![image](https://cloud.githubusercontent.com/assets/5743135/9159626/81310940-3f56-11e5-833b-f08bbed7056c.png)

# Proposed solution
make it happy :)

**Comment by ismailsunni** [comment]
This is related to #2078 
cc @timlinux

**Comment by timlinux** [comment]
Hi @cchristelis I looks like this might be coming from your reports mixin - could you take a look please?

**Comment by adissadis** [comment]
I also encountered this issue when running flood on population

**Comment by Charlotte-Morgan** [comment]
still getting this error and if i click in dock and open in browser i get the error message there too

**Comment by cchristelis** [comment]
The fix only addressed vector flood on buildings.
@adissadis, which scenario did you use when encountering the flood on population error? I think we should open a new ticket for that as the problem in this issue is related to the buildings report, which does not have an effect on on population scenarios.

**Comment by cchristelis** [comment]
Hi @Charlotte-Morgan, after applying this fix, I am no longer getting this issue on my machine. Please confirm that this problem is resolved in the latest develop.

**Comment by Charlotte-Morgan** [comment]
Hi @cchristelis - perfect - fixed for me too. thanks !
