### ISSUE TITLE
News from HOT-OSM blog that related to InaSAFE

### ISSUE THREAD

**Issue by samnawi** [AIFDR/inasafe#2216]
Hi @MariaSolovyeva 
Last week @Charlotte-Morgan ask to me to looking for the news from OSM-ID Blog (http://openstreetmap.id/en/blog/) that related with InaSAFE.
This is some news that I found in there :

The Public Consultation of Disaster Risk Assessment in South Sulawesi
http://openstreetmap.id/en/konsultasi-publik-kajian-risiko-bencana-sulawesi-selatan/
Workshop I Disaster Risk Assessment in South Sulawesi
http://openstreetmap.id/en/lokakarya-i-kegiatan-kajian-risiko-bencana-di-sulawesi-selatan/
The Second Workshop
of Disaster Risk Assessment in South Sulawesi
http://openstreetmap.id/en/lokakarya-ii-kajian-risiko-bencana-di-sulawesi-selatan/
QGIS Application Training in Disaster Risk Assessment, Nagekeo – NTT
http://openstreetmap.id/en/pelatihan-aplikasi-qgis-dalam-kajian-risiko-bencana-di-nagekeo-ntt/
Risk Assessment Workshop in TTU, East Nusa Tenggara
http://openstreetmap.id/en/pelatihan-dan-lokakarya-kajian-resiko-bencana-di-ttu-nusa-tenggara-timur/
April 2015 MeetUp : Learning OSM and Understanding InaSAFE
http://openstreetmap.id/en/kopi-darat-bulan-april-2015-belajar-osm-dan-memahami-inasafe/
Community MeerUp April 2015
http://openstreetmap.id/en/kopi-darat-komunitas-bulan-april-2015/
InaSAFE Workshop Session 1
http://openstreetmap.id/en/inasafe-workshop-sesi-1/
OSM, QGIS, and InaSAFE Training in BPBD Lembata
http://openstreetmap.id/en/pelatihan-osm-qgis-dan-inasafe-di-bpbd-lembata/
InaSAFE Socialisation to BPBD Representatives
http://openstreetmap.id/en/kegiatan-sosialisasi-inasafe/
Alumni Training in Scenario Development for Contingency Planning using InaSAFE 2.0
http://openstreetmap.id/en/pelatihan-alumni-pengembangan-skenario-untuk-rencana-kontinjensi-dengan-inasafe-2-0/
Disaster Risk Analysis Training for BPBD of East Nusa Tenggara
http://openstreetmap.id/en/pelatihan-analisa-risiko-bencana-bpbd-pronvinsi-nusa-tenggara-timur/
Updated Data to Support Makassar Flood Contingency Plan
http://openstreetmap.id/en/update-data-untuk-rencana-kontijensi-banjir-kota-makassar/
InaSAFE Socialization to BPBDs in Central Java Province
http://openstreetmap.id/en/sosialisasi-inasafe-ke-bpbd-se-jawa-tengah/
Contingency Plan development in Makassar
http://openstreetmap.id/en/penyusunan-rencana-kontijensi-banjir-kota-makassar/
Bengawan Solo Mapping to Support Contingency Plan
http://openstreetmap.id/en/pemetaan-bengawan-solo-dalam-rangka-penyusunan-rencana-kontijensi-banjir-bengawan-solo/

@Charlotte-Morgan ask me to find this stuff, and send this link to @MariaSolovyeva in order that put this news also in the new InaSAFE Blog.

Thank You

cc : @adissadis @iyan31

**Comment by Charlotte-Morgan** [comment]
Hi @maria - could you please add links to these materials on the new InaSAFE web site?

#cc
@timlinux

**Comment by iyan31** [comment]
Hello all,

Since August 2014, most of InaSAFE-related post in http://openstreetmap.id have been cross-posted in http://blog.inasafe.org/ too. Are we going to keep the http://blog.inasafe.org/ as the main repository for InaSAFE post or alternatively The InaSAFE blog can also retrieve InaSAFE-related post from http://openstreetmap.id using RSS feed (for example, http://openstreetmap.id/en/tag/inasafe/feed/ to retrieve all post with InaSAFE tags)

**Comment by Charlotte-Morgan** [comment]
@iyan31 - thanks for explaining. Maybe I missed something because I looked at the new InaSAFE web site and thought that there is a lot of great work HOT has been doing that is missing. If there is already cross posting - that is wonderful and we can keep doing this. Maybe @MariaSolovyeva can just check that the posts from InaSAFE website are copied across to the new web site.
@iyan31  - are there also some articles and links in the list above that might not already be cross posted? eg the contingency planning etc that we could cross post?

**Comment by MariaSolovyeva** [comment]
Hi @all - OK! I will copy all the posts today and will see through the links if something is missed or  not

**Comment by iyan31** [comment]
Hi @Charlotte-Morgan,

Yes surely there are articles that we haven't cross posted, especially for articles prior to August 2014. I can work on the cross posting next week, after I got back from Manila.

**Comment by timlinux** [comment]
@iyan31 yes just to confirm, what is currently hosted as http://blogtest.inasafe.org will become the new http://inasafe.org and the old blog site will be abandoned.

**Comment by MariaSolovyeva** [comment]
Hi @all 

I have added the missed articles to the http://blogtest.inasafe.org/blog
