### ISSUE TITLE
Report: Scale bar is not visible

### ISSUE THREAD

**Issue by roscoeKartoza** [AIFDR/inasafe#2253]
# Problem
The scale bar below the map is not visible. 

![no_scale_bar](https://cloud.githubusercontent.com/assets/10434570/9493033/045888d6-4bfd-11e5-95a0-94eb32d987ea.png)

# Environment 
In Windows as well as OSX.

# Proposed Solution
Opening the template and deleting the scalebar and creating the bar again with the same attributes seemed to work.

**Comment by samnawi** [comment]
Hi @roscoeKartoza 
In a couple of days ago, I've been created a new template for InaSAFE.
But it's still no scalebar, because It's still complicated to set the scale bar in here.
Like the fix the width --> although it available in QGIS 2.10
Set the number in scale bar, because it will be confuse if the user use the geographic system coordinate, and not activate the OTF.

I've been explained about it in the issue #1314 
Maybe you have any advice to fix the problem?

Thank you.

**Comment by timlinux** [comment]
For now I will remove the scalebar in our standard template - in next LTR we can add it back as it will have constrained width support
