### ISSUE TITLE
Add a Note in All Impact Function

### ISSUE THREAD

**Issue by samnawi** [AIFDR/inasafe#2388]
# Problem
When we doing systematics testing, we found that there is no Note in the roads impact (Both of flood and tsunami).
![selection_228](https://cloud.githubusercontent.com/assets/8871958/9955336/545fa72c-5e1a-11e5-8f15-2766c6175dd2.png)

# Proposed Solution
Give notes in here, to explain about the data and the process.

# CC
@Charlotte-Morgan @fredychandra @timlinux 

Thankyou

**Comment by timlinux** [comment]
Can you provide some input on what you would like to see in the notes please?

**Comment by fredychandra** [comment]
Propose notes for road IF, Flood and Tsunami 

This is for Flood impact report
1. Roads are flooded when flood levels exceed **1.0 m**
2. Roads are closed if they are flooded 
3. Roads are open if they are not flooded

This is for Tsunami Impact report
1. Roads are inundated when water levels exceed **1.0 m**
2. Roads are closed if they are inundated 
3. Roads are open if they are not inundated

**This value** should be read from user threshold in the impact function

**Comment by ismailsunni** [comment]
Hi @fredychandra 
Thanks for the notes.

Btw, we also have flood polygon on road. And the notes above can't be applied in this IF since we use attribute value to identify which polygon is inundated. For example, in attribute FLOODPRONE, and the value can be YES / NO.

If you have notes for this IF, I can add it to the IF on version 3.2.1.

We can use the same notes for point 2 and 3. But for point 1, we can't. I suggest something like:

Roads are flooded when it's located on hazard polygon that has [flood value] in [attribute].

May be you can give a better alternative.

Thanks.

**Comment by samnawi** [comment]
@ismailsunni My propose for point1, can we use like in the building?
So, the note will written like this :
1. Roads are said to be inundated when in a region with field "FLOODPRONE" in "YES" .

cc : @Charlotte-Morgan how about this?

**Comment by ismailsunni** [comment]
@samnawi That's better. I will change it.
