### ISSUE TITLE
Bug: new map templates

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2403]
The new map templates look very smart; however there are a few bugs.
- [ ] no default template is set.
- [ ] no disclaimer appearing on A3 portrait or landscape blue
- [ ] something has happened to the coordinates - what are these numbers? (it used to be in degrees)
- [x] template names "A3 - portrait - blue" might be a more logical naming convention

papercut
- [ ] do we need the top level heading for the layer in the legend. ie in the example below I think we only need the "estimated buildings affected" not the "structure inundated status"
![image](https://cloud.githubusercontent.com/assets/5743135/9978996/755d9e84-5f7d-11e5-815f-770136061d73.png)

# cc
@samnawi @adissadis - please review the changes to templates and advice what impact it has on training materials & screenies

**Comment by timlinux** [comment]
Templates renamed in timlinux/inasafe@952c601

> something has happened to the coordinates - what are these numbers? (it used to be in degrees)

I actually never changed anything on the map element  - I will take a look...my guess is you are using on the fly projection?

**Comment by Charlotte-Morgan** [comment]
update - testing on another machine - coords are fine, disclaimer appears but the old one not the new one.

**Comment by samnawi** [comment]
@Charlotte-Morgan I've tried to run the newest pull, but this is my result, depend of your list :
- [ ] no default template is set. --> **yes** for the first
- [ ] no disclaimer appearing on A3 portrait or landscape blue --> **no**, the disclaimer is appear in my result
![selection_231](https://cloud.githubusercontent.com/assets/8871958/9984659/1e982df2-6046-11e5-91b2-b71b5bc03505.png)
- [ ] something has happened to the coordinates - what are these numbers? (it used to be in degrees) --> yes, it's because the OTF is activated
- [ ] template names "A3 - portrait - blue" might be a more logical naming convention --> It' OK

# Question
Why I get the different north arrow for my result?
This is in Charlotte's result (and also in my windows PC)
![selection_232](https://cloud.githubusercontent.com/assets/8871958/9984727/25d90ff4-6047-11e5-852e-eb755c6c9b44.png)
This is the north arrow that I get when I use my Linux PC
![selection_233](https://cloud.githubusercontent.com/assets/8871958/9984730/377ba00a-6047-11e5-8be2-e512e63fa6c8.png)

**Comment by timlinux** [comment]
> no default template is set.
> no disclaimer appearing on A3 portrait or landscape blue


For the record these are local configurations side effects from your InaSAFE options

> something has happened to the coordinates - what are these numbers? (it used to be in degrees)

I think your map is using on the fly projection (not fully supported yet in InaSAFE).

**Comment by Charlotte-Morgan** [comment]
thanks - i think you are correct.
Nothing here that cant wait till 3.2.1
