### ISSUE TITLE
QGIS crash (not responding) when running volcano analysis

### ISSUE THREAD

**Issue by emirhartato** [AIFDR/inasafe#928]
# Problem
QGIS crash (not responding) when running volcano analysis using volcano point (Smithsonian) and AsiaPop raster population. There is no error message, I did wait until an hour but nothing happened, so I have to force closed the apps.

# System
QGIS 2.2 Valmiera (64-bit)
InaSAFE 2.0.5 (Downloaded from QGIS Repo)
Windows 8.1 Pro 64-Bit Build 9600
Intel i7 4700HQ 2.4Ghz
RAM 4GB

# Data
Merapi point: https://www.dropbox.com/s/cgtdgl50k23h3ux/merapi.zip

Due to large file, you can get AsiaPop Indonesian population (2010) from here: http://www.clas.ufl.edu/users/atatem/index_files/Indonesia.htm

**Comment by akbargumbira** [comment]
hey @emirhartato, we have changed the behavior for this analysis! For the point hazard IF (at the moment we only have Volcano Point on Population), if there is user analysis extent, we clip the exposure to that extent. If that extent does intersect with the point hazard extent, it will run the analysis. Otherwise, it will tell you that the extents are not overlapped to each other.

Note that for that IF there is also an option in which you can set the radii of the point to buffer. If that extent is smaller than the buffer, it will not show you all the buffered area.

I am closing this
